import type { ShapeReference } from './geometry';
import type { SketchElement, SketchPlane } from './sketch-elements';
import type { OperationParams } from './operation-params';
import type { FeatureTool, Tool, ToolCategory } from './tools';

export interface Sketch {
  id: string;
  name: string;
  /** Sketch plane definition */
  plane: SketchPlane;
  /** 2D geometry elements in this sketch */
  elements: SketchElement[];
  /** Reference to the OpenCascade wire/face generated from this sketch */
  geometry?: ShapeReference;
  /** Whether the sketch is closed (can be used for extrude/revolve) */
  isClosed: boolean;
  /** Whether this sketch is visible in the viewport */
  isVisible: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface Feature {
  id: string;
  name: string;
  type: FeatureTool;
  /** Reference to source sketch (for sketch-based operations) */
  sketchId?: string;
  /** Operation parameters (distance, angle, radius, etc.) */
  parameters?: OperationParams;
  /** Reference to the OpenCascade shape generated by this feature */
  geometry?: ShapeReference;
  /** Parent feature IDs (for dependency tracking) */
  parentIds: string[];
  /** Whether this feature is currently suppressed (not included in rebuild) */
  isSuppressed: boolean;
  /** Whether this feature is visible in the viewport */
  isVisible: boolean;
  createdAt: number;
  updatedAt: number;
  isExpanded?: boolean;
}

export interface ReferenceGeometry {
  id: string;
  name: string;
  type: 'plane' | 'origin';
  isVisible: boolean;
}

export interface FeatureTreeItem {
  id: string;
  name: string;
  type: 'reference-geometry' | 'sketch' | 'feature';
  children?: FeatureTreeItem[];
  isExpanded?: boolean;
  visible?: boolean;
  error?: string;
  data?: ReferenceGeometry | Sketch | Feature;
}

export interface CADProject {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  /** Version number for parametric rebuild tracking */
  version: number;
  referenceGeometry: ReferenceGeometry[];
  sketches: Sketch[];
  features: Feature[];
}

/** Rebuild state tracking */
export interface RebuildState {
  /** Whether a rebuild is currently in progress */
  isRebuilding: boolean;
  /** Current rebuild progress (0-1) */
  progress: number;
  /** Error message if rebuild failed */
  error?: string;
  /** ID of feature currently being rebuilt */
  currentFeatureId?: string;
}

export interface CADState {
  project: CADProject;
  activeTab: ToolCategory;
  activeTool: Tool;
  selectedTreeItem: string | null;
  isSidebarOpen: boolean;
  /** Current rebuild state */
  rebuildState: RebuildState;
  /** Active sketch being edited (if in sketch mode) */
  activeSketchId: string | null;
}

// Default reference geometry that always exists
export const DEFAULT_REFERENCE_GEOMETRY: ReferenceGeometry[] = [
  { id: 'front-plane', name: 'Front Plane', type: 'plane', isVisible: false },
  { id: 'top-plane', name: 'Top Plane', type: 'plane', isVisible: false },
  { id: 'right-plane', name: 'Right Plane', type: 'plane', isVisible: false },
  { id: 'origin', name: 'Origin', type: 'origin', isVisible: false },
];

export const createNewProject = (): CADProject => {
  const now = Date.now();
  const defaultSketchId = crypto.randomUUID();
  const defaultExtrudeId = crypto.randomUUID();

  return {
    id: crypto.randomUUID(),
    name: 'Untitled Project',
    createdAt: now,
    updatedAt: now,
    version: 1,
    referenceGeometry: DEFAULT_REFERENCE_GEOMETRY,
    sketches: [
      {
        id: defaultSketchId,
        name: 'Sketch1',
        plane: {
          type: 'xy',
          planeRef: 'front-plane',
          offset: 0,
        },
        elements: [
          {
            type: 'rectangle',
            corner1: { x: -25, y: -25 },
            corner2: { x: 25, y: 25 },
          } as SketchElement,
        ],
        isClosed: true,
        isVisible: false,
        createdAt: now,
        updatedAt: now,
      },
    ],
    features: [
      {
        id: defaultExtrudeId,
        name: 'Boss-Extrude1',
        type: 'extrude-boss',
        sketchId: defaultSketchId,
        parameters: {
          distance: 50,
          direction: { x: 0, y: 0, z: 1 },
          isCut: false,
        },
        parentIds: [defaultSketchId],
        isSuppressed: false,
        isVisible: true,
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
};
