import { ShapeReference } from '../geometry/ShapeReference';
import { OperationParams } from '../operations/OperationParams';
import { FeatureOperation } from '../operations/FeatureOperation';

export interface Feature {
  id: string;
  name: string;
  type: FeatureOperation;
  /** Reference to source sketch (for sketch-based operations) */
  sketchId?: string;
  /** Operation parameters (distance, angle, radius, etc.) */
  parameters?: OperationParams;
  /** Reference to the OpenCascade shape generated by this feature */
  geometry?: ShapeReference;
  /** Parent feature IDs (for dependency tracking) */
  parentIds: string[];
  /** Whether this feature is currently suppressed (not included in rebuild) */
  isSuppressed: boolean;
  /** Whether this feature is visible in the viewport */
  isVisible: boolean;
  createdAt: number;
  updatedAt: number;
  isExpanded?: boolean;
  /**
   * Explicit build-order override (epoch-ms domain). Set when the feature is
   * reordered in the tree; when unset, ordering falls back to `createdAt`.
   * See {@link OrderableItem} / `compareBuildOrder`.
   */
  sequence?: number;
}
