import { ShapeReference } from '../geometry/ShapeReference';
import { OperationParams } from '../operations/OperationParams';
import { FeatureTool } from '../tools/FeatureTool';

export interface Feature {
  id: string;
  name: string;
  type: FeatureTool;
  /** Reference to source sketch (for sketch-based operations) */
  sketchId?: string;
  /** Operation parameters (distance, angle, radius, etc.) */
  parameters?: OperationParams;
  /** Reference to the OpenCascade shape generated by this feature */
  geometry?: ShapeReference;
  /** Parent feature IDs (for dependency tracking) */
  parentIds: string[];
  /** Whether this feature is currently suppressed (not included in rebuild) */
  isSuppressed: boolean;
  /** Whether this feature is visible in the viewport */
  isVisible: boolean;
  createdAt: number;
  updatedAt: number;
  isExpanded?: boolean;
}
