import { ShapeReference } from '../geometry/shapeRefs';
import { OperationParams } from '../operations/OperationParams';
import { FeatureOperation } from '../operations/FeatureOperation';
import { Operation, OperationCategory } from '../operations/Operation';
import { ReferenceGeometry } from './ReferenceGeometry';
import { Sketch } from '../sketch/Sketch';

export interface Feature {
  id: string;
  name: string;
  type: FeatureOperation;
  /** Reference to source sketch (for sketch-based operations) */
  sketchId?: string;
  /** Operation parameters (distance, angle, radius, etc.) */
  parameters?: OperationParams;
  /** Reference to the OpenCascade shape generated by this feature */
  geometry?: ShapeReference;
  /** Parent feature IDs (for dependency tracking) */
  parentIds: string[];
  /** Whether this feature is currently suppressed (not included in rebuild) */
  isSuppressed: boolean;
  /** Whether this feature is visible in the viewport */
  isVisible: boolean;
  createdAt: number;
  updatedAt: number;
  isExpanded?: boolean;
  /**
   * Explicit build-order override (epoch-ms domain). Set when the feature is
   * reordered in the tree; when unset, ordering falls back to `createdAt`.
   * See {@link OrderableItem} / `compareBuildOrder`.
   */
  sequence?: number;
}

export interface CADProject {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  /** Version number for parametric rebuild tracking */
  version: number;
  referenceGeometry: ReferenceGeometry[];
  sketches: Sketch[];
  features: Feature[];
  /**
   * History rollback marker (SolidWorks-style rollback bar). A threshold in the
   * `orderKey` (epoch-ms) domain: any sketch/feature whose build-order key is
   * **strictly greater** than this is "rolled back" — skipped during rebuild and
   * greyed in the feature tree, but not deleted. `undefined` means the bar is at
   * the bottom (nothing rolled back). See `isRolledBack` and ROADMAP.md §8.
   */
  rollbackBar?: number;
}

/** Rebuild state tracking */
export interface RebuildState {
  /** Whether a rebuild is currently in progress */
  isRebuilding: boolean;
  /** Current rebuild progress (0-1) */
  progress: number;
  /** Error message if rebuild failed */
  error?: string;
  /** ID of feature currently being rebuilt */
  currentFeatureId?: string;
}

export interface CADState {
  project: CADProject;
  activeTab: OperationCategory;
  activeOperation: Operation;
  selectedTreeItem: string | null;
  isSidebarOpen: boolean;
  /** Current rebuild state */
  rebuildState: RebuildState;
  /** Active sketch being edited (if in sketch mode) */
  activeSketchId: string | null;
}

export enum FeatureTreeItemType {
  REFERENCE_GEOMETRY = 'reference-geometry',
  SKETCH = 'sketch',
  FEATURE = 'feature'
}

export interface FeatureTreeItem {
  id: string;
  name: string;
  type: FeatureTreeItemType;
  children?: FeatureTreeItem[];
  isExpanded?: boolean;
  visible?: boolean;
  /** True when the item falls after the history rollback bar (greyed, not built). */
  rolledBack?: boolean;
  error?: string;
  data?: ReferenceGeometry | Sketch | Feature;
}
